"""empty message

Revision ID: 081ece820a2f
Revises: c66783a9d6c0
Create Date: 2025-03-02 19:52:43.160456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081ece820a2f'
down_revision = 'c66783a9d6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'form_categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['deleter_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('form_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('deleter_id')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
