"""empty message

Revision ID: 1722ca8eef8a
Revises: 66cedc709741
Create Date: 2025-03-05 17:15:26.947281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1722ca8eef8a'
down_revision = '66cedc709741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('showoff_attributes', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('showoff_attributes')

    # ### end Alembic commands ###
