"""empty message

Revision ID: 1b2210a21554
Revises: 9392ccd42165
Create Date: 2025-03-15 22:14:59.467037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2210a21554'
down_revision = '9392ccd42165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_fields', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_categories', schema=None) as batch_op:
        batch_op.drop_column('common_fields')

    # ### end Alembic commands ###
