"""empty message

Revision ID: 2f3241c4e7db
Revises: 5df14bcf364e
Create Date: 2025-03-16 23:14:27.714487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3241c4e7db'
down_revision = '5df14bcf364e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_non_approved_submissions', sa.Boolean(), server_default=sa.text("'false'::boolean"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_column('has_non_approved_submissions')

    # ### end Alembic commands ###
