"""empty message

Revision ID: 48341d1f4d24
Revises: 506b647e8177
Create Date: 2025-02-25 20:50:44.602926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48341d1f4d24'
down_revision = '506b647e8177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
