"""empty message

Revision ID: 506b647e8177
Revises: 7ea2bd9aab08
Create Date: 2025-02-25 20:36:38.376262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506b647e8177'
down_revision = '7ea2bd9aab08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_invite_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint('roles_invite_code_key', ['invite_code'])

    # ### end Alembic commands ###
