"""empty message

Revision ID: 62e0a5ca5865
Revises: 5457c2df8c06
Create Date: 2025-03-01 20:02:04.116588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e0a5ca5865'
down_revision = '5457c2df8c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_types', schema=None) as batch_op:
        batch_op.drop_column('params')

    # ### end Alembic commands ###
