"""empty message

Revision ID: 66cedc709741
Revises: 081ece820a2f
Create Date: 2025-03-02 23:04:08.274570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cedc709741'
down_revision = '081ece820a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_types_form_categories',
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('form_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_category_id'], ['form_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_type_id', 'form_category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object_types_form_categories')
    # ### end Alembic commands ###
