"""empty message

Revision ID: 72079e52eb11
Revises: 1722ca8eef8a
Create Date: 2025-03-05 17:51:35.726819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72079e52eb11'
down_revision = '1722ca8eef8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('showoff_attributes')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('showoff_attributes', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('showoff_attributes')

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('showoff_attributes', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
