"""empty message

Revision ID: 9245734e3598
Revises: 93943033b791
Create Date: 2025-03-16 23:57:39.085648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9245734e3598'
down_revision = '93943033b791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_column('backup')

    # ### end Alembic commands ###
