"""empty message

Revision ID: 93943033b791
Revises: 2f3241c4e7db
Create Date: 2025-03-16 23:22:31.330826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93943033b791'
down_revision = '2f3241c4e7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_unapproved_submissions', sa.Boolean(), server_default=sa.text("'false'::boolean"), nullable=False))
        batch_op.drop_column('has_non_approved_submissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_non_approved_submissions', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('has_unapproved_submissions')

    # ### end Alembic commands ###
