"""empty message

Revision ID: 9c8d9a8e1304
Revises: b2b3adf6b5ba
Create Date: 2025-03-24 15:06:09.774391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8d9a8e1304'
down_revision = 'b2b3adf6b5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('backup')

    # ### end Alembic commands ###
