"""empty message

Revision ID: a53450e43b8a
Revises: e35e072f1dfd
Create Date: 2025-03-16 18:08:11.269079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53450e43b8a'
down_revision = 'e35e072f1dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default=sa.text("'true'::boolean"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
