"""empty message

Revision ID: f848e0fce248
Revises: 72079e52eb11
Create Date: 2025-03-09 11:17:19.215877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f848e0fce248'
down_revision = '72079e52eb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleter_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['deleter_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=True))
        batch_op.add_column(sa.Column('form_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('form_category_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), server_default=sa.text("'false'::boolean"), nullable=False))
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
        batch_op.alter_column('form_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_external')
        batch_op.drop_column('form_category_name')
        batch_op.drop_column('form_name')
        batch_op.drop_column('fields')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('deleter_id')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
